In [2]:
import numpy
import numpy as np

Specifiy 5 pixels position relative to center of detector:
 - lower left corner
 - upper left corner
 - lower right corner
 - upper right corner
 - lower left center

In [5]:
det_pos_list = [[0.149854,-0.149854,0.], [0.149854,0.149854,0.], [-0.149854,-0.149854,0.],
                [-0.149854,0.149854,0.], [0.000146484,-0.000146484,0.]]

det_pos_array = np.array(det_pos_list)

Definition of operation

In [8]:
def set_arm(det_pos_array, r):
    """ move from origin to +Z (arm distance)
    """
    det_pos_array[:, 2] += r
    
    return det_pos_array

In [18]:
def rotate_axis_x(det_pos_array, angle_degree):
    """ rotate a set of positions along X axis
    """
        # build rotation matrix
    angle_rad = angle_degree * numpy.pi / 180.
    rotate_matrix = numpy.matrix([[1., 0., 0.],
                                  [0., numpy.cos(angle_rad), -numpy.sin(angle_rad)],
                                  [0., numpy.sin(angle_rad), numpy.cos(angle_rad)]],
                                 'float')
    rotated_pixel_matrix = rotate_matrix * det_pos_array.transpose()
    
    return rotated_pixel_matrix.transpose()

In [13]:
def rotate_axis_y(det_pos_array, angle_degree):
    """ rotate a set of positions around Y axis
    """
    # build rotation matrix
    angle_rad = angle_degree * numpy.pi / 180.
    rotate_matrix = numpy.matrix([[numpy.cos(angle_rad), 0., numpy.sin(angle_rad)],
                                  [0., 1., 0.],
                                  [-numpy.sin(angle_rad), 0., numpy.cos(angle_rad)]],
                                 'float')
    rotated_pixel_matrix = rotate_matrix * det_pos_array.transpose()
    
    return rotated_pixel_matrix.transpose()

In [21]:
def rotate_axis_z(det_pos_array, angle_degree):
    """ rotate a set of positions around Z axis
    """
    # build rotation matrix
    angle_rad = angle_degree * numpy.pi / 180.
    rotate_matrix = numpy.matrix([[numpy.cos(angle_rad), -numpy.sin(angle_rad), 0.],
                                  [numpy.sin(angle_rad), numpy.cos(angle_rad), 0.],
                                  [0., 0., 1.]],
                                 'float')
    rotated_pixel_matrix = rotate_matrix * det_pos_array.transpose()
    
    return rotated_pixel_matrix.transpose()

#### Test 1: Move along +Z direction (step 1)

In [12]:
raw_pos_array = np.matrix(det_pos_list)
step1_pos = set_arm(raw_pos_array, 0.95)
print (step1_pos)

[[  1.49854000e-01  -1.49854000e-01   9.50000000e-01]
 [  1.49854000e-01   1.49854000e-01   9.50000000e-01]
 [ -1.49854000e-01  -1.49854000e-01   9.50000000e-01]
 [ -1.49854000e-01   1.49854000e-01   9.50000000e-01]
 [  1.46484000e-04  -1.46484000e-04   9.50000000e-01]]


#### Test 2: Move along +Z, Rotate along Y-axis for 90 degree

In [15]:
raw_pos_array = np.matrix(det_pos_list)
step1_pos = set_arm(raw_pos_array, 0.95)
step2_pos = rotate_axis_y(step1_pos, -90.)  # must be negative
print (step2_pos)

[[ -9.50000000e-01  -1.49854000e-01   1.49854000e-01]
 [ -9.50000000e-01   1.49854000e-01   1.49854000e-01]
 [ -9.50000000e-01  -1.49854000e-01  -1.49854000e-01]
 [ -9.50000000e-01   1.49854000e-01  -1.49854000e-01]
 [ -9.50000000e-01  -1.46484000e-04   1.46484000e-04]]


#### Test 3: Rotate along X-axis for 15 degree (flip), Move along +Z

In [20]:
raw_pos_array = np.matrix(det_pos_list)
step1_pos = rotate_axis_x(raw_pos_array, 15.)  # must be negative
step2_pos = set_arm(step1_pos, 0.95)
print (step2_pos)

[[  1.49854000e-01  -1.44747849e-01   9.11214931e-01]
 [  1.49854000e-01   1.44747849e-01   9.88785069e-01]
 [ -1.49854000e-01  -1.44747849e-01   9.11214931e-01]
 [ -1.49854000e-01   1.44747849e-01   9.88785069e-01]
 [  1.46484000e-04  -1.41492679e-04   9.49962087e-01]]


#### Test 4: Rotate along Z-axis for 5 degree (Spin), Move along +Z

In [22]:
raw_pos_array = np.matrix(det_pos_list)
step1_pos = rotate_axis_z(raw_pos_array, 5.)
step2_pos = set_arm(step1_pos, 0.95)
print (step2_pos)

[[  1.62344397e-01  -1.36223124e-01   9.50000000e-01]
 [  1.36223124e-01   1.62344397e-01   9.50000000e-01]
 [ -1.36223124e-01  -1.62344397e-01   9.50000000e-01]
 [ -1.62344397e-01   1.36223124e-01   9.50000000e-01]
 [  1.58693506e-04  -1.33159662e-04   9.50000000e-01]]


#### Test 5: Rotate along Z-axis (5 degree), Rotate along X-axis (15 degree), Move along +Z

In [23]:
raw_pos_array = np.matrix(det_pos_list)
step1_pos = rotate_axis_z(raw_pos_array, 5.)
step2_pos = rotate_axis_x(step1_pos, 15.)
step3_pos = set_arm(step2_pos, 0.95)
print (step3_pos)

[[  1.62344397e-01  -1.31581433e-01   9.14742861e-01]
 [  1.36223124e-01   1.56812646e-01   9.92017822e-01]
 [ -1.36223124e-01  -1.56812646e-01   9.07982178e-01]
 [ -1.62344397e-01   1.31581433e-01   9.85257139e-01]
 [  1.58693506e-04  -1.28622357e-04   9.49965536e-01]]


#### Test 6: Rotate along X-axis (15 degree), Rotate along Z-axis (5 degree), Move along +Z

In [24]:
raw_pos_array = np.matrix(det_pos_list)
step1_pos = rotate_axis_x(raw_pos_array, 15.)
step2_pos = rotate_axis_z(step1_pos, 5.)
step3_pos = set_arm(step2_pos, 0.95)
print (step3_pos)

[[  1.61899367e-01  -1.31136403e-01   9.11214931e-01]
 [  1.36668154e-01   1.57257676e-01   9.88785069e-01]
 [ -1.36668154e-01  -1.57257676e-01   9.11214931e-01]
 [ -1.61899367e-01   1.31136403e-01   9.88785069e-01]
 [  1.58258484e-04  -1.28187335e-04   9.49962087e-01]]


#### Test 7: Rotate along X-axis (15 degree), Rotate along Z-axis (5 degree), Move along +Z, rotate detector to 2theta=85.

In [26]:
raw_pos_array = np.matrix(det_pos_list)
step1_pos = rotate_axis_x(raw_pos_array, 15.)
step2_pos = rotate_axis_z(step1_pos, 5.)
step3_pos = set_arm(step2_pos, 0.95)
step4_pos = rotate_axis_y(step3_pos, -90.)
print (step4_pos)

[[ -9.11214931e-01  -1.31136403e-01   1.61899367e-01]
 [ -9.88785069e-01   1.57257676e-01   1.36668154e-01]
 [ -9.11214931e-01  -1.57257676e-01  -1.36668154e-01]
 [ -9.88785069e-01   1.31136403e-01  -1.61899367e-01]
 [ -9.49962087e-01  -1.28187335e-04   1.58258484e-04]]
